export interface KotItem {

attributeId?: string;
attributeName?: string;
billId?:string;
billNo?: string;
catAttributeMapping?: any[];
catId?: string;
catName?: string;
catTax?: any[];
categoryCode?: string;
chQty?: number;
changeQuantity?: string;
completedTime?: string;
date?: string;
draftItemId?: string;
draftSId?: string;
er4uInd?: string;
finalQuantity?: string;
hsn?: string;
itemCost?: string;
itemStatus?: string;
kotId?: string;
kotItemId?:string;
kotSId?: string;
locationId?: string;
modifyRemark?: string;
modifyRemarkTime?: string;
name?: string;
netAmt?: string;
qty?: number;
rate?: number;
remark?: string;
rowStatus?: string;
status?: string;
tblRmName?: string;
totalAmount?: string;
totalCost?: string;
totalQuantity?: string;
totalRate?: number;
type?: string;
type_refId?: string;
userId?: string;
value1?: string;
value2?: string;
value3?: string;
value4?: string;
value5?: string;
value6?: string;
value7?: string;
value8?: string;
value9?: string;
value10?: string;
value11?: string;
value12?: string;
value13?: string;
value14?: string;
value15?: string;
value16?: string;
value17?: string;
waiterId?: string;
waiterName?: string;

}
