import { Item } from './item';
import { KotItem } from './kot-item';

export interface Kot {
billId?:string;
billNo?:string;
cQty?:string;
cancelKotComment?:string;
comment?:string;
completedTime?: string;
customerId?:string;
date?:string;
dis?: string;
draftItemId?: string;
draftSId?: string;
homeDeliveryPersonId?: string;
item?: Item[];
itemStatus?:string;
kotId?:string;
kotItem?: KotItem[];
kotSId?: string;
logoName?: string;
netAmt?: string;
qty?: string;
rate?: string;
rowStatus?: string;
status?: string;
tableName?: string;
thirdPartyId?: string;
totalAmt?: string;
totalQty?: string;
totalRate?: string;
type?: string;
type_refId?: string;
value1?: string;
value2?: string;
value3?: string;
value4?: string;
value5?: string;
value6?: string;
value7?: string;
value8?: string;
value9?: string;
value10?: string;
value11?: string;
value12?: string;
value13?: string;
value14?: string;
value15?: string;
value16?: string;
value17?: string;
waiterId?: string;
waiterName?: string;
}
